dist: xenial
sudo: true
cache: pip

matrix:
  include:
    - language: python
      python: "3.7"
      install:
        - pip install -r requirements.txt
      script:
        - pytest --cov=core
    - language: node_js
      node_js:
        - "lts/carbon"

      sources:
      - google-chrome
      packages:
      - google-chrome-stable

      env:
        - DJANGO_VERSION=2.1.2 DB=postgresql DISPLAY=:99.0 CHROME_BIN=/usr/bin/google-chrome DJANGO_HOST=http://127.0.0.1:8000/api

      install:
        # installs the packages specified in package.json
        - cd react
        - npm install

      before_script:
        # Allows us to run chrome in travis
        - Xvfb :99 &
        - sleep 3 # give xvfb some time to start

      script:
        # enforces front-end code styling
        - npm run-script lint
        # runs the front-end unit tests and coverage
        - npm test -- --single-run