# Generated by Django 2.1.5 on 2019-03-14 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-published']},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-published']},
        ),
    ]
