# Generated by Django 2.1.5 on 2019-03-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='authors.Author'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_author', to='authors.Author'),
        ),
        # manually smooshed in
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-published']},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-published']},
        ),
    ]
