# Generated by Django 2.1.7 on 2019-03-19 23:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0005_auto_20190312_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='visibility',
            field=models.CharField(
                choices=[('PUBLIC', 'Public'), ('FOAF', 'Friend of a Friend'), ('FRIENDS', 'Friends'),
                         ('PRIVATE', 'Private'), ('SERVERONLY', 'Server Only')], default='PUBLIC', max_length=10),
        ),
        migrations.AlterField(
            model_name='posts',
            name='visibleTo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=None),
        ),
    ]
