# Generated by Django 2.1.5 on 2019-04-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190319_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.URLField(),
        ),
    ]
