# Generated by Django 2.1.5 on 2019-02-06 22:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=80)),
                ('github', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
