# Generated by Django 2.1.5 on 2019-02-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.URLField()),
                ('followed', models.URLField()),
                ('friends', models.BooleanField(default=False)),
            ],
        ),
    ]
