# Generated by Django 2.1.5 on 2019-02-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_friendrequest_requester_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
