# Generated by Django 2.1.5 on 2019-02-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_author_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
