# Generated by Django 2.1.5 on 2019-02-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_auto_20190221_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='requester_name',
        ),
    ]
