# Generated by Django 2.1.5 on 2019-03-25 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='base_url',
            field=models.CharField(default='Test', max_length=250, validators=[django.core.validators.RegexValidator('\\/$', 'The base URL should not end with a slash.')]),
            preserve_default=False,
        ),
    ]
