# Generated by Django 2.1.5 on 2019-03-25 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_server_base_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='name',
        ),
        migrations.AddField(
            model_name='server',
            name='fetch_posts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='fetching_password',
            field=models.CharField(default='Test', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='fetching_username',
            field=models.CharField(default='test', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='base_url',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('\\/$', 'The base URL should not end with a slash.', inverse_match=True)]),
        ),
    ]
