# Generated by Django 2.1.7 on 2019-03-26 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20190325_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='base_url',
            field=models.CharField(blank=True, max_length=250, validators=[django.core.validators.RegexValidator('\\/$', 'The base URL should not end with a slash.', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='server',
            name='fetching_password',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='server',
            name='fetching_username',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
