# Generated by Django 2.1.7 on 2019-03-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20190326_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='is_server',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
